targets:
  $default:
    sources:
      - lib/**
      - lib/specs/**
      - $package$
      - test/**.dart
      - integration_test/**.dart
    builders:
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
          - test_integration/**.dart
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/specs"
          output_folder: "lib/generated/"