name: Cryptstorage
on: [push]
jobs:
  check:
    runs-on: linux
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    # Download all Flutter packages
    - name: Download dependencies
      run: flutter pub get

    # Check for any formatting issues in the code.
    - name: check code format
      run: flutter format --set-exit-if-changed .

    # Run Flutter Analyzer
    - name: Run Flutter Analyzer
      run: flutter analyze

    # Run all unit-tests with code coverage
    - name: Run unit tests
      run: flutter test --coverage
  build_apk:
    runs-on: linux
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - name: 'Upload Android Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: yubidrive.aab
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 7
  build_ios:
    runs-on: macOS
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: 'Upload iOS Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Yubidrive.app
        path: /Users/runner/work/cryptstorage_app/cryptstorage_app/build/ios/iphoneos/Runner.app
        retention-days: 7
  deploy_ios:
    name: Deploy iOS Beta
    needs: [build_ios]
    runs-on: macOS
    steps:
     - uses: actions/checkout@v3
     - uses: actions/download-artifact@v3
       with:
         name: Yubidrive.app
     - uses: maierj/fastlane-action@v2.2.1
       with:
         lane: 'beta'
         subdirectory: 'ios'
  deploy_apk:
    name: Deploy Android Beta
    needs: [build_apk]
    runs-on: linux
    steps:
     - uses: actions/checkout@v3
     - uses: actions/download-artifact@v3
       with:
         name: yubidrive.aab
     - name: Create Google Play Config file
       run: |
         echo "$PLAY_CONFIG_JSON" > play_config.json.b64
         base64 -d -i play_config.json.b64 > play_config.json
       env:
         PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
     - uses: maierj/fastlane-action@v2.2.1
       with:
         lane: 'beta'
         subdirectory: 'android'
  release:
    runs-on: linux
    needs: [ios, android]
    steps:
    - uses: actions/checkout@v3
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
    - name: Create the Mattermost Message
      run: |
        echo "{\"text\":\"Build completed. [Get APK]($RUN_URL). :tada:\"}" > mattermost.json
      env:
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    - uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}