name: Cryptstorage
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    # Download all Flutter packages
    - name: Download dependencies
      run: flutter pub get

    # Check for any formatting issues in the code.
    - name: check code format
      run: flutter format --set-exit-if-changed .

    # Run Flutter Analyzer
    - name: Run Flutter Analyzer
      run: flutter analyze

    # Run all unit-tests with code coverage
    - name: Run unit tests
      run: flutter test --coverage
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - name: 'Upload Android Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: yubidrive.apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 7
  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: 'Upload iOS Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Yubidrive.app
        path: /Users/runner/work/cryptstorage_app/cryptstorage_app/build/ios/iphoneos/Runner.app
        retention-days: 7
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Create the Mattermost Message
      run: |
        echo "{\"text\":\"Build completed. [Get APK]($RUN_URL). :tada:\"}" > mattermost.json
      env:
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    - uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}